spring:
  application:
    name: demo
  profiles:
    active: dev
    group:
      dev:
        - "dev"
        - "dev-pg"
        - "dev-redis"
albert:
  swagger:
    token:
      header: Authorization
  security:
    token:
      header: Authorization