server:
  port: 9000
  servlet:
    context-path: /demo
logging:
  level:
    root: info
    com.albert.auth.mapper: debug
#    org.springframework.jdbc.core.JdbcTemplate: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    local-cache-scope: statement
albert:
  swagger:
    token:
      header: Authorization
  security:
    token:
      header: Authorization
  front-end:
    url: http://localhost:3000